### ISSUE TITLE
DG comments

### ISSUE THREAD

**Issue by joelczk** [AY2021S1-CS2113T-W12-4/tp#285]
Some comments for your DG:
1. [x] Please try to use standard UML notations from the module. Examples like <<singleton>> are custom decorators in PlantUML, and not a standard notation for DG diagrams
2. [x] There are missing `:` in class names for many of the diagrams 
![image](https://user-images.githubusercontent.com/42378287/97652682-f2c13980-1a99-11eb-91c3-d2ebd42ddb57.png)
3. [x] There seems to be a missing activation bar when `decodeEventList` is being called(red). I think you are trying to do minimal notation of the diagrams, but this leads to some ambiguity.
4. [x] Is the activation bar supposed to persist beyond the loop(blue)?
![image](https://user-images.githubusercontent.com/42378287/97653102-f0abaa80-1a9a-11eb-969b-92aae2a54d9f.png)
5. [x] Missing activation bar when `decodeEventToString` is called(red)
6. [x] The dotted arrows representing the return from the function call and the rectangle representing the loop are overlapping each other, which makes it hard for the reader to see(blue)
![image](https://user-images.githubusercontent.com/42378287/97653528-f1910c00-1a9b-11eb-9a2e-d313758e0f3f.png)
7. [x] There should an activation bar when `refreshQuizzes()` is called, assuming that this is a self-invocation method call. I think you are trying to do minimal notation of the diagrams, but this leads to some ambiguity.
![image](https://user-images.githubusercontent.com/42378287/97653829-a7f4f100-1a9c-11eb-93f6-50b022704b68.png)
8. [x] There should be an activation bar when `decodeQuizFromString` is called, assuming that this is a self-invocation method call(red). I think you are trying to do minimal notation of the diagrams, but this leads to some ambiguity.
9. [x] Placing the delete ('x' icon) on the same level as the dotted lines representing the return arrows. It is recommended that you put the delete icon below, along the lifeline of the `File` class to avoid confusion(blue)
![image](https://user-images.githubusercontent.com/42378287/97654970-04591000-1a9f-11eb-9970-b2b90fce7619.png)
10. [x] Missing return arrows from `handleHelp`
![image](https://user-images.githubusercontent.com/42378287/97655181-73366900-1a9f-11eb-87f7-209ab6e24e34.png)
11. [x] Overlapping activation bars, which makes it very confusing where the return arrow is coming from
![image](https://user-images.githubusercontent.com/42378287/97655687-9dd4f180-1aa0-11eb-9d29-b94013d75d4e.png)
12. [x] Placing the delete ('x' icon) on the same level as the dotted lines representing the return arrows. It is recommended that you put the delete icon below, along the lifeline of the `FindSchedule` class to avoid confusion(blue)
13. [x] `Quiz Feature` contains a chunk of text that is quite wordy to read. Maybe you can consider to break it down into point form for easier readability
14. [x] Similiarly,`Saving Data` contains a chunk of text that is very wordy to read. Maybe you can consider breaking it down into point forms for easier readability.

**Comment by durianpancakes** [comment]
Partially addressed by #345
