### ISSUE TITLE
[bug] Setting recommended hours directly in txt file will circumvent restriction

### ISSUE THREAD

**Issue by AndreWongZH** [AY2021S1-CS2113T-W12-4/tp#403]
![image](https://user-images.githubusercontent.com/21986187/98463300-3849d900-21f5-11eb-8635-875e0d62b54a.png)
I can put 0 for the recommended hours

![image](https://user-images.githubusercontent.com/21986187/98463318-531c4d80-21f5-11eb-8d65-3fdd0cfe410e.png)
Application fails if i put a non number.

**Comment by durianpancakes** [comment]
I will handle this. Thanks for raising the issue.
